#baseurl: "/dizer-jekyll" # the subpath of your site, e.g. /blog
url: "https://www.findemor.es" # the base hostname & protocol for your site, e.g. http://example.com or  https://Dizerjk.netlify.com
title: "findemor gamedev"
email: "contacto@findemor.es"
#phone: "+21 123 456 5523"
#address: "9567 Turner Trace Apt. 466 North Willie, BC C3G8A4"
author: findemor
description: >- # this means to ignore newlines
  Cursos gratuitos, devlogs, recursos y comunidad para aprender a hacer videojuegos con Godot 4 desde cero. Crea tus propios juegos con ejemplos reales.
logo: "/assets/images/logo.png"
# contact form action (FormSubmit)
contact_form_action: "https://formsubmit.co/contacto@findemor.es"
#mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"
footer_content: "También comparto ideas, opiniones y tonterías por aquí."
copyright: "findemor. &copy; 2025 All Right Reserved"
# page header default image
cover_image: "/assets/images/bg/about-bg.jpg"
#google_map_api: "https://maps.googleapis.com/maps/api/js?key=AIzaSyDnh74UN6BKgq9U5fMNGhdZOSpmM_QnZqs"


################## Social site ###############
social:
  - name: youtube
    icon: "fa-brands fa-youtube"
    link: "https://www.youtube.com/@findemor"

  - name: twitter
    icon: "fa-brands fa-x-twitter"
    link: "https://x.com/findemor"

  - name: bsky
    icon: "fa-brands fa-bluesky"
    link: "https://bsky.app/profile/findemor.bsky.social"

  - name: instagram
    icon: "fa-brands fa-instagram"
    link: "http://instagram.com/findemor.es"

  - name: twitch
    icon: "fa-brands fa-twitch"
    link: "http://twitch.com/findemor"

# Build settings
permalink: "/:title"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives

# Scss Directory
sass:
  sass_dir: assets/scss
  style: compressed

#collections
collections:
  recursos:
    output: true
  juegos:
    output: true

########################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination page
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 12

  # The permalink structure for the paginated pages (this can be any level deep)
  #permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  permalink: "/blog/:num/" # Pages are simple html file
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"

  # Optional, the default tag to use, omit to disable
  tag: ""

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""

  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: "html"

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index"

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

feed:
  collections:
    posts:
      path: "/blog.xml"
    juegos:
      path: "/juegos.xml"
